### ISSUE TITLE
get_leaderboard_ids - Elo 

### ISSUE THREAD

**Issue by quincyc3** [idraper/terminal_svr#1]
elo = algo['elo'] 
should be 
elo = algo['rating']

**Comment by idraper** [comment]
Yeah, it looks like there were several changes with getting some information with season 2, like also getting the leaderboard metrics keys have changed. Thanks for pointing it out! I'll push some changes tonight.

**Comment by idraper** [comment]
@quincyc3 this has been fixed, thanks :).
